//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupplierDocuments.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierDocument
    {
        public int SupplierDocumentID { get; set; }
        public int SupplyingRegionID { get; set; }
        public int SupplyingCountryID { get; set; }
        public int SupplierLocationID { get; set; }
        public int SupplierTypeID { get; set; }
        public int DocumentID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
