//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupplierDocuments.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierContact
    {
        public int ContactID { get; set; }
        public int SupplierID { get; set; }
        public string ContactName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public bool IsPrimary { get; set; }
    
        public virtual SupplierContact SupplierContacts1 { get; set; }
        public virtual SupplierContact SupplierContact1 { get; set; }
    }
}
